SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO




-- =============================================
-- Author:		GL Legacy
-- Modified by: Freddy
-- Modified dt: 05/11/2022
-- =============================================
CREATE       VIEW [dbo].[vStudents]
AS

SELECT 
	GradeLev,
	Access,
	EncKey,
	MissedPasswords,
	LanguageType,
	LastLoginTime,
	xStudentID,
	StudentID,
	FamilyID,
	Family2ID,
	FamilyOrTempID,
	Active,
	Lname,
	Mname,
	Fname,
	suffix,
	Nickname,
	GradeLevX,
	GradeLevel,
	Class,
	Father,
	Mother,
	Phone1,
	Phone2,
	Phone3,
	Phone1OptIn,
	Phone2OptIn,
	Phone3OptIn,
	Family2Phone1OptIn,
	Family2Phone2OptIn,
	Email1,
	Email2,
	Email3,
	Email4,
	Email5,
	Email6,
	Email7,
	Email8,
	SchoolEmail,
	Family2Name1,
	Family2Name2,
	Family2Phone1,
	Family2Phone2,
	StudentLivesWithFather,
	StudentLivesWithMother,
	StudentLivesWithStepfather,
	StudentLivesWithStepmother,
	StudentLivesWithGuardian1,
	StudentLivesWithGuardian2,
	StudentLivesWithOther,
	StudentLivesWithDesc,
	Divorced,
	Custody,
	BirthDate,
	Sex,
	AddressDescription,
	AddressName,
	Street,
	City,
	[State],
	Zip,
	CountryRegion,
	CityStateZip1,
	AddressDescription2,
	AddressName2,
	Street2,
	City2,
	State2,
	Zip2,
	CountryRegion2,
	CityStateZip2,
	EntryDate,
	WithdrawalDate,
	GraduationDate,
	Comments,
	Comments2,
	Comments3,
	LockerNumber,
	LockerCode,
	AccountID,
	FullName,
	ActiveOrInactive,
	_Status,
	Affiliations,
	[Status],
	Parents,
	Emails,
	Phones,
	isHispanicLatino,
	isCatholic,
	isTitle1eligible,
	isTitle1receiving,
	isNSLPbreakfast,
	isLunchEligible,
	isNSLPlunch,
	isSubsidizedTrans,
	isPromoteToCatholicHS,
	isSpecialEdReceiving,
	isDiagnosedDisability,
	isInternational,
	isChoiceProgram,
	Degree,
	Major,
	WithdrawReason,
	EnableStudentLockerInfo,
	EnableHispanicEthnicityQuestion,
	isCatholicSchool,
	isADLACensus,
	showSISlabels,
	AdultSchool,
	GeneralizeGuardianLabels,
	EnableDegreeAndMajor,
	SchoolState,
	ShowEthnicityRace,
	WISEid,
	CountyName,
	CountyName2,
	GradeLevWI,
	Full_Name,
	'abc' AS test
FROM dbo.fn_vStudents();

GO
