CREATE TYPE [dbo].[StudentImportTableType] AS TABLE
(
[xStudentID] [bigint] NULL,
[AccountID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Password] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lname] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fname] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mname] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Nickname] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GradeLevel] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Class] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BirthDate] [smalldatetime] NULL,
[Sex] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ethnicity] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LockerNumber] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LockerCode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Father] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mother] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressDescription] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Street] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zip] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressDescription2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Street2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zip2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone3] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email1] [nvarchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email2] [nvarchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email6] [nvarchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email7] [nvarchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email8] [nvarchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SchoolEmail] [nvarchar] (70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
