CREATE TABLE [dbo].[AuditPDFInvoices]
(
[SearchFromDate] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SearchThruDate] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SessionTitle] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FamilyID] [int] NULL,
[FamilySortOrderByMaxStudentName] [nvarchar] (61) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StudentID] [int] NOT NULL,
[Lname] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FullName] [nvarchar] (92) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[xStudentID] [bigint] NOT NULL,
[AddressName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Street] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zip] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReceivableID] [int] NULL,
[Date] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransactionType] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Notes] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContractID] [int] NULL,
[TransactionMethod] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReferenceNumber] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SignedAmount] [money] NULL,
[DB_CR_Code] [nchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[month] [nvarchar] (61) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriorBal] [money] NULL,
[Balance] [money] NOT NULL,
[SortOrder] [nvarchar] (49) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Family_CtStZp] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SchoolName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SchoolStreet] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[School_CtStZp] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SchoolPhone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SchoolFax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SchoolEmailAddress] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TaxID] [nchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PriorBalance] [money] NOT NULL,
[BillingNote] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SchoolID] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EK] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[runTime] [datetime] NULL
) ON [PRIMARY]
GO
