CREATE TABLE [dbo].[TagBinFiles]
(
[TBID] [int] NOT NULL IDENTITY(1, 1),
[TagID] [int] NOT NULL,
[FileID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TagBinFiles] ADD CONSTRAINT [PK_TagBinFiles] PRIMARY KEY CLUSTERED ([TBID]) WITH (FILLFACTOR=95) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_FileID] ON [dbo].[TagBinFiles] ([FileID]) WITH (FILLFACTOR=95) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TagBinFiles] ADD CONSTRAINT [FK_TagBinFiles_BinFiles] FOREIGN KEY ([FileID]) REFERENCES [dbo].[BinFiles] ([FileID]) ON DELETE CASCADE
GO
