CREATE TABLE [dbo].[TagStaff]
(
[TSID] [int] NOT NULL IDENTITY(1, 1),
[TagID] [int] NOT NULL,
[TeacherID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TagStaff] ADD CONSTRAINT [PK_TagStaff] PRIMARY KEY CLUSTERED ([TSID]) WITH (FILLFACTOR=95) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_TeacherID] ON [dbo].[TagStaff] ([TeacherID]) WITH (FILLFACTOR=95) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TagStaff] ADD CONSTRAINT [FK_TagStaff_Teachers] FOREIGN KEY ([TeacherID]) REFERENCES [dbo].[Teachers] ([TeacherID]) ON DELETE CASCADE
GO
