CREATE TABLE [dbo].[Transcript]
(
[TranscriptID] [int] NOT NULL IDENTITY(1, 1),
[TermID] [int] NOT NULL,
[TermTitle] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TermReportTitle] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TermStart] [datetime] NOT NULL,
[TermEnd] [datetime] NOT NULL,
[ParentTermID] [int] NOT NULL CONSTRAINT [DF_Transcript_ParentTermID] DEFAULT ((0)),
[TermWeight] [decimal] (5, 2) NULL,
[ExamTerm] [bit] NOT NULL CONSTRAINT [DF_Transcript_ExamTerm] DEFAULT ((0)),
[StudentID] [int] NOT NULL,
[GradeLevel] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Fname] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Mname] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lname] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[StaffTitle] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TFname] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TLname] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TermComment] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClassID] [int] NOT NULL CONSTRAINT [DF_Transcript_ClassID] DEFAULT ((0)),
[ClassTitle] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpanishTitle] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportOrder] [int] NOT NULL CONSTRAINT [DF_Transcript_ReportOrder] DEFAULT ((0)),
[ClassTypeID] [int] NOT NULL,
[ParentClassID] [int] NOT NULL CONSTRAINT [DF_Transcript_ParentClassID] DEFAULT ((0)),
[SubCommentClassTypeID] [int] NOT NULL CONSTRAINT [DF_Transcript_SubCommentClassTypeID] DEFAULT ((0)),
[CustomGradeScaleID] [smallint] NOT NULL CONSTRAINT [DF_Transcript_CustomGradeScaleID] DEFAULT ((0)),
[ClassUnits] [decimal] (10, 6) NULL,
[UnitsEarned] [decimal] (10, 6) NULL,
[Period] [int] NULL,
[LetterGrade] [nvarchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AlternativeGrade] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClassLevel] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PercentageGrade] [decimal] (5, 2) NULL,
[UnitGPA] [decimal] (7, 4) NULL,
[CustomFieldName] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomFieldSpanishName] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomFieldGrade] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomFieldOrder] [int] NULL,
[FieldBolded] [bit] NOT NULL CONSTRAINT [DF_Transcript_FieldBolded] DEFAULT ((0)),
[FieldNotGraded] [bit] NOT NULL CONSTRAINT [DF_Transcript_FieldNotGraded] DEFAULT ((0)),
[Indent] [tinyint] NULL CONSTRAINT [DF_Transcript_Indent] DEFAULT ((0)),
[Bullet] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_Transcript_Bullet] DEFAULT ('none'),
[GradeScaleLegend] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportSectionTitle] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Effort] [tinyint] NULL,
[ClassComments] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Att1] [smallint] NULL,
[PercAtt1] [decimal] (5, 2) NULL,
[Att2] [smallint] NULL,
[PercAtt2] [decimal] (5, 2) NULL,
[Att3] [smallint] NULL,
[PercAtt3] [decimal] (5, 2) NULL,
[Att4] [smallint] NULL,
[PercAtt4] [decimal] (5, 2) NULL,
[Att5] [smallint] NULL,
[PercAtt5] [decimal] (5, 2) NULL,
[SchoolAtt1] [decimal] (5, 2) NULL,
[PercSchoolAtt1] [decimal] (5, 2) NULL,
[SchoolAtt2] [decimal] (5, 2) NULL,
[PercSchoolAtt2] [decimal] (5, 2) NULL,
[SchoolAtt3] [decimal] (5, 2) NULL,
[PercSchoolAtt3] [decimal] (5, 2) NULL,
[SchoolAtt4] [decimal] (5, 2) NULL,
[PercSchoolAtt4] [decimal] (5, 2) NULL,
[SchoolAtt5] [decimal] (5, 2) NULL,
[PercSchoolAtt5] [decimal] (5, 2) NULL,
[SchoolAtt6] [decimal] (5, 2) NULL,
[PercSchoolAtt6] [decimal] (5, 2) NULL,
[SchoolAtt7] [decimal] (5, 2) NULL,
[PercSchoolAtt7] [decimal] (5, 2) NULL,
[SchoolAtt8] [decimal] (5, 2) NULL,
[PercSchoolAtt8] [decimal] (5, 2) NULL,
[SchoolAtt9] [decimal] (5, 2) NULL,
[PercSchoolAtt9] [decimal] (5, 2) NULL,
[SchoolAtt10] [decimal] (5, 2) NULL,
[PercSchoolAtt10] [decimal] (5, 2) NULL,
[SchoolAtt11] [decimal] (5, 2) NULL,
[PercSchoolAtt11] [decimal] (5, 2) NULL,
[SchoolAtt12] [decimal] (5, 2) NULL,
[PercSchoolAtt12] [decimal] (5, 2) NULL,
[SchoolAtt13] [decimal] (5, 2) NULL,
[PercSchoolAtt13] [decimal] (5, 2) NULL,
[SchoolAtt14] [decimal] (5, 2) NULL,
[PercSchoolAtt14] [decimal] (5, 2) NULL,
[SchoolAtt15] [decimal] (5, 2) NULL,
[PercSchoolAtt15] [decimal] (5, 2) NULL,
[ChurchPresent] [smallint] NULL,
[PercChurchPresent] [decimal] (5, 2) NULL,
[ChurchAbsent] [smallint] NULL,
[PercChurchAbsent] [decimal] (5, 2) NULL,
[SSchoolPresent] [smallint] NULL,
[PercSSchoolPresent] [decimal] (5, 2) NULL,
[SSchoolAbsent] [smallint] NULL,
[PercSSchoolAbsent] [decimal] (5, 2) NULL,
[Exceptional] [smallint] NULL,
[PercExceptional] [decimal] (5, 2) NULL,
[Good] [smallint] NULL,
[PercGood] [decimal] (5, 2) NULL,
[Poor] [smallint] NULL,
[PercPoor] [decimal] (5, 2) NULL,
[Unacceptable] [smallint] NULL,
[PercUnacceptable] [decimal] (5, 2) NULL,
[CommentName] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CommentAbbr] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment1] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment2] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment3] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment4] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment5] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment6] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment7] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment8] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment9] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment10] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment11] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment12] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment13] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment14] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment15] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment16] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment17] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment18] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment19] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment20] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment21] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment22] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment23] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment24] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment25] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment26] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment27] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment28] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment29] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment30] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryAbbr] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Category1Symbol] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Category1Desc] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Category2Symbol] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Category2Desc] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Category3Symbol] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Category3Desc] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Category4Symbol] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Category4Desc] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConcludeDate] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPABoost] [decimal] (5, 2) NOT NULL CONSTRAINT [DF_Transcript_GPABoost] DEFAULT ((0)),
[CalculateGPA] [bit] NOT NULL CONSTRAINT [DF_Transcript_CalculateGPA] DEFAULT ((1)),
[IgnoreTranscriptGradeLevelFilter] [bit] NOT NULL CONSTRAINT [DF_Transcript_IgnoreTranscriptGradeLevelFilter] DEFAULT ((0)),
[GradReqCategoryID] [int] NULL,
[GradReqCategoryHistoryID] [int] NULL,
[StandardsItemType] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CourseCode] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OldStudentID] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Rigor] [bit] NOT NULL CONSTRAINT [DF__Transcrip__Rigor__10B8C3E9] DEFAULT ((0)),
[DualEnrollment] [bit] NOT NULL CONSTRAINT [DF__Transcrip__DualE__11ACE822] DEFAULT ((0)),
[StandardsGradeScaleID] [tinyint] NOT NULL CONSTRAINT [DF_Transcript_StandardsGradeScaleID] DEFAULT ((0)),
[Nickname] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tglname] AS (case isnull(session_context(N'AdminLanguage'),'English') when 'Chinese' then [TLname]+[TFname] else ([TLname]+', ')+[TFname] end),
[Suffix] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sglname] AS (case isnull(session_context(N'AdminLanguage'),'English') when 'Chinese' then [Lname]+[Fname] else ((([Lname]+', ')+[Fname])+case  when len(ltrim(rtrim([Mname])))>(0) then (' '+left([Mname],(1)))+'.' else '' end)+case  when len(ltrim(rtrim([Suffix])))>(0) then ', '+[Suffix] else '' end end+case  when len(ltrim(rtrim([NickName])))>(0) then (' ('+[NickName])+')' else '' end),
[PostSecondaryInstitution] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditType] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HighSchoolLevel] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Transcript] ADD CONSTRAINT [PK_Transcript] PRIMARY KEY CLUSTERED ([TranscriptID]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_GradReqCategoryHistoryID] ON [dbo].[Transcript] ([GradReqCategoryHistoryID]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_StudentID] ON [dbo].[Transcript] ([StudentID]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_Transcript_StudentID_TermID_ClassTitle] ON [dbo].[Transcript] ([StudentID], [TermID], [ClassTitle]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Transcript] ADD CONSTRAINT [IX_Transcript] UNIQUE NONCLUSTERED ([TermID], [TermTitle], [StudentID], [ClassTypeID], [ClassTitle], [CustomFieldOrder]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Transcript] ADD CONSTRAINT [FK_Transcript_GradReqCategoryHistory] FOREIGN KEY ([GradReqCategoryHistoryID]) REFERENCES [dbo].[GradReqCategoryHistory] ([CHistoryID])
GO
ALTER TABLE [dbo].[Transcript] ADD CONSTRAINT [FK_Transcript_Students] FOREIGN KEY ([StudentID]) REFERENCES [dbo].[Students] ([StudentID])
GO
