CREATE TABLE [dbo].[AuditWISEdata]
(
[RecordID] [int] NOT NULL IDENTITY(1, 1),
[AdminID] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SnapshotPeriod] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ResourceType] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[WISEdataRecordID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[WISEid] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[StudentID] [int] NOT NULL,
[xStudentID] [int] NULL,
[TransactionDateTime] [datetime] NOT NULL,
[Fname] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Lname] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Birthdate] [datetime] NULL,
[DateEnteredUS] [datetime] NULL,
[EconomicDisadvantaged] [bit] NULL,
[SchoolFoodServicesElig] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LimitedEnglishProficiency] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HispanicLatinoEthnicity] [bit] NULL,
[StudentRace] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StudentCharacteristics] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StudentDisabilities] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrimaryDisability] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SAschoolId] [int] NULL,
[SAschoolYear] [int] NULL,
[SAentryDate] [datetime] NULL,
[EntryGradeLevel] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExitDate] [datetime] NULL,
[ExitWithdrawlType] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrimarySchool] [bit] NULL,
[WEentryDate] [datetime] NULL,
[ExpectedTransferEdOrg] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExpectedTransferSchool] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CompletedTerm] [bit] NULL,
[ActualDaysAttendance] [decimal] (10, 2) NULL,
[PossibleDaysAttendance] [decimal] (10, 2) NULL,
[SchoolChoiceParticipant] [bit] NULL,
[ReceivingServices1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReceivingServicesValue1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReceivingServices2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReceivingServicesValue2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARschoolId] [int] NULL,
[ARschoolYear] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARterm] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Diploma1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiplomaAwardDate1] [datetime] NULL,
[Diploma2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiplomaAwardDate2] [datetime] NULL,
[Diploma3] [nchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiplomaAwardDate3] [datetime] NULL,
[StudentLanguages] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StudentVisas] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[widpiStudentResidentEduOrg] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WiDpiProgramScheduleType] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RepeatGradeIndicator] [bit] NULL,
[SPeducationOrgId] [int] NULL,
[ProgramType] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProgramName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SPbeginDate] [datetime] NULL,
[SPendDate] [datetime] NULL,
[SEeducationorgid] [int] NULL,
[SEprogramType] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SEprogramName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SEfapeschoolid] [int] NULL,
[SEbegindate] [datetime] NULL,
[SEenddate] [datetime] NULL,
[ideaeligibility] [bit] NULL,
[IEPbegindate] [datetime] NULL,
[IEPenddate] [datetime] NULL,
[SEsettingdescriptor] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SEparentplacedprivate] [bit] NULL,
[multiplebirthstatus] [bit] NULL,
[othernames] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[birthcountry] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[foodbegindate] [datetime] NULL,
[foodenddate] [datetime] NULL,
[AddressTypeDescriptor] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StateAbbreviationDescriptor] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PostalCode] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StreetNumberName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[birthcity] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[birthstate] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AuditWISEdata] ADD CONSTRAINT [PK_AuditWISEdata] PRIMARY KEY CLUSTERED ([RecordID]) WITH (FILLFACTOR=95) ON [PRIMARY]
GO
