CREATE TABLE [dbo].[PS_API_Payments]
(
[CustomerId] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerFirstName] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerLastName] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerCompany] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReferenceId] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecurringScheduleId] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PaymentType] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PaymentSubType] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderAuthCode] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TraceNumber] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PaymentDate] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReturnDate] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EstimatedSettleDate] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EstimatedDepositDate] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActualSettledDate] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CanVoidUntil] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PS_API_Payments_Id] [int] NOT NULL,
[RequiresReceipt] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CVV] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountId] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InvoiceId] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsDebit] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InvoiceNumber] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PurchaseOrderNumber] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderId] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Latitude] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Longitude] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SuccessReceiptOptions] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KryptonOrderId] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FailureReceiptOptions] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Id] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastModified] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedOn] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UniqueID] [int] NOT NULL IDENTITY(1, 1),
[UpdateTime] [datetime] NULL CONSTRAINT [DefaultUpdateTime] DEFAULT (getdate()),
[CardOnFileType] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Resubmission] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
