CREATE TABLE [dbo].[PSCCCardTypes]
(
[PSCCTypeID] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PSCCType] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PSCCCardTypes] ADD CONSTRAINT [PK_PSCCCardTypes_PSCCTypeID] PRIMARY KEY CLUSTERED ([PSCCTypeID]) WITH (FILLFACTOR=95) ON [PRIMARY]
GO
