IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'BACKEND\IUSR_BACKEND')
CREATE LOGIN [BACKEND\IUSR_BACKEND] FROM WINDOWS
GO
CREATE USER [BACKEND\IUSR_BACKEND] FOR LOGIN [BACKEND\IUSR_BACKEND]
GO
